# Generated by Django 3.2.8 on 2021-10-07 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='phoneNumber',
            new_name='phone',
        ),
    ]
