# Generated by Django 3.2.8 on 2021-11-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_img',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
