# Generated by Django 3.2.8 on 2021-11-01 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_product_img_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_img',
            name='productID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.product'),
        ),
    ]
