# Generated by Django 3.2.7 on 2021-10-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_phonenumber_customer_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=100)),
                ('unitPrice', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
                ('quantityInStock', models.IntegerField()),
                ('showcasedImg', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Product_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productID', models.IntegerField()),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
