# Generated by Django 3.2.8 on 2021-11-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_product_img_productid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('incart', 'Trong giỏ hàng'), ('processing', 'Đang xử lý'), ('done', 'Đã hoàn thành')], default='inCart', max_length=20),
        ),
    ]
