# Generated by Django 3.2.8 on 2021-10-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20211030_1837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='productName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='unitPrice',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
    ]
