# Generated by Django 3.2.8 on 2021-11-14 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(max_length=32),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('iphone', 'iphone'), ('ipad', 'ipad'), ('mac', 'mac'), ('watch', 'watch')], default='iphone', max_length=100),
        ),
    ]
