# Generated by Django 3.2.8 on 2021-11-20 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20211120_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='xom',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
