# Generated by Django 3.2.8 on 2021-11-21 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20211121_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='huyen',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='tinh',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='xa',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='xom',
        ),
    ]
