# Generated by Django 3.2.7 on 2021-11-26 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20211121_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_color',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=10)),
                ('productID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.product')),
            ],
        ),
        migrations.RemoveField(
            model_name='xa',
            name='huyen',
        ),
        migrations.DeleteModel(
            name='Huyen',
        ),
        migrations.DeleteModel(
            name='Tinh',
        ),
        migrations.DeleteModel(
            name='Xa',
        ),
    ]
