# Generated by Django 3.2.7 on 2021-11-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20211126_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_color',
            name='productID',
            field=models.CharField(max_length=32),
        ),
    ]
