# Generated by Django 3.2.7 on 2021-11-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_product_img_productid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_img',
            name='color',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
