# Generated by Django 3.2.7 on 2021-11-26 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_product_img_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_img',
            old_name='image',
            new_name='img',
        ),
    ]
