# Generated by Django 3.1.7 on 2021-11-27 06:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_product_capacity_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_img',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.product_img'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
