# Generated by Django 3.1.7 on 2021-11-27 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20211127_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='color',
        ),
        migrations.AddField(
            model_name='order',
            name='productImg',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
