# Generated by Django 3.1.7 on 2021-11-27 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20211127_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='productCapacity',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
