# Generated by Django 3.2.9 on 2021-11-30 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20211127_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_img_color',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.product'),
        ),
    ]
