# Generated by Django 3.2.9 on 2021-11-30 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20211130_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_capacity',
            name='product123',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.product'),
        ),
    ]
