# Generated by Django 3.2.9 on 2021-11-30 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_rename_product123_product_capacity_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_capacity',
            name='product456',
        ),
    ]
