# Generated by Django 3.2.9 on 2021-12-08 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_customer_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
    ]
