# Generated by Django 3.2.9 on 2021-12-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_remove_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('incart', 'Trong giỏ hàng'), ('processing', 'Đang xử lý'), ('shipping', 'Đang giao hàng'), ('done', 'Đã hoàn thành')], default='inCart', max_length=20),
        ),
    ]
